services:

  web:
    image: 321869098112.dkr.ecr.us-east-1.amazonaws.com/visitor-counter:v1
    container_name: visitor-counter

    ports:
      - "80:5000"

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes

    restart: unless-stopped

volumes:
  redis-data: